<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>DLBeastSaveManager</AssemblyName>
    <RootNamespace>DLBeastSaveManager</RootNamespace>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Version>1.0.0</Version>
    <Product>DL:TB Save Manager</Product>
    <Description>Save backup manager for Dying Light The Beast </Description>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

</Project>
